src/lib/components/Select.svelte
src/lib/types/reporting.ts
src/routes/+layout.ts
src/routes/projects/new/ProjectContentSelector.svelte
src/routes/reporting/+page.svelte
src/routes/reporting/+page.ts
src/routes/reporting/[slug]/+page.svelte
src/routes/reporting/[slug]/+page.ts
src/routes/resources/+page.svelte

add dynamic report dropdown to reporting page and language/parent resource filters

---

.github/workflows/post-merge.yml
.github/workflows/pre-merge.yml

Forgot to remove these references which were causing errors on dependabot PRs.

remove remaining private repo references

---

src/app.d.ts
src/lib/components/editorMarkPopouts/VersePopout.svelte
src/lib/components/references/BibleTextReference.svelte
src/lib/components/references/bibleTextReferenceFetcher.ts
src/lib/components/tiptap/bibleReferenceMark.ts
src/lib/utils/bible-passage-fetcher.ts
src/lib/utils/bible-passage-utils.ts
src/routes/resources/[resourceContentId]/BibleReferencesSidebar.svelte

handle multi-verse references in verse popout

---

src/lib/types/resources.ts
src/routes/(dashboard)/+page.ts
src/routes/(dashboard)/PublisherDashboard.svelte
src/routes/(dashboard)/publisher-dashboard-columns.ts

Add ResourceContentVersionReviewLevel enum to client 
Update 'Assign' button logic

Add Community tab to Publisher Dashboard

---

src/lib/components/Table.svelte
src/lib/components/projects/ProjectTable.svelte
src/lib/components/projects/ProjectViewTableAndFilters.svelte
src/routes/(dashboard)/EditorDashboard.svelte
src/routes/(dashboard)/ManagerDashboard.svelte
src/routes/(dashboard)/PublisherDashboard.svelte

In order to support the community reviewer resources search we need to have pagination. This PR adds it to the Table component and adjusts some CSS in various spots the Table is used, in order to standardize. Also fixes a couple small bugs I found.

add pagination to table component and fix a couple small bugs

---

src/routes/(dashboard)/CommunityReviewerDashboard.svelte

Removed relevant css to remove horizontal scroll bars on Edge browser

---

src/routes/resources/[resourceContentId]/+page.svelte

When a Community user takes action (send to publisher or creates translation), that users ability to translate more resources was not properly being tracked. 
From Community User Dashboard:
- Search for resources - select a book and click `Apply`
- select a resource and navigate to its page
- Click `Translate`
- Click `Exit` or navigate back to `Dashboard` via hamburger menu
- Perform a new search and select `Apply`
- View a new resource
The `translate` button will show when a community user should not see it.
This also does not display the `translate` button when the user has sent their last translation to review.

Add toggle state on community user action

---

src/lib/components/Table.svelte
src/lib/components/reporting/BarChart.svelte
src/lib/components/reporting/LineChart.svelte
src/lib/types/base.ts
src/lib/types/reporting.ts
src/routes/reporting/[slug]/+page.svelte
src/routes/reporting/[slug]/+page.ts
src/routes/reporting/[slug]/BarChart.svelte
src/routes/reporting/[slug]/LineChart.svelte

Another piece prepping for the projects reporting tab.

refactor BarChart and LineChart to generic components and add company picker to dynamic report

---

package.json
src/lib/charts/TotalResourcesAreaChart.svelte
src/lib/charts/TranslatedResourcesBarChart.svelte
src/lib/components/Table.svelte
src/lib/components/editor/EditorToolbar.svelte
src/lib/components/projects/ProjectDelivery.svelte
src/lib/components/projects/ProjectOverview.svelte
src/lib/components/projects/ProjectQuote.svelte
src/lib/components/projects/ViewTabSlot.svelte
src/routes/(dashboard)/CommunityReviewerDashboard.svelte
src/routes/(dashboard)/EditorDashboard.svelte
src/routes/(dashboard)/ManagerDashboard.svelte
src/routes/(dashboard)/PublisherDashboard.svelte
src/routes/projects/ProjectReportingTab.svelte
src/routes/reporting/+page.svelte
yarn.lock

Also makes sure the table above loads in first so we get the correct size for the charts when they load.

update Tailwind, remove some px usage, and handle shorter browsers by scrolling project reporting tab

---

src/lib/components/help/Document.svelte
src/lib/components/help/HelpScreen.svelte
src/lib/components/help/List.svelte
src/routes/+layout.svelte

- Update Navigation menu to be visible when help screen open
- Close Help screen on navigate
- PDFs open in new tab
- css adjustments

QA UX adjustments

---

src/app.d.ts
src/lib/components/editorMarkPopouts/ResourcePopout.svelte
src/lib/components/tiptap/extensions/resource-reference.ts
src/routes/resources/[resourceContentId]/+page.svelte

add resource reference inline popout

---

src/routes/resources/[resourceContentId]/sidebar-content-store.ts

Removed Name From Ai Translation Snapshot

---

src/lib/components/help/Document.svelte
src/lib/components/help/List.svelte
src/routes/help/+page.svelte

make help document titles more readable

---

src/routes/resources/[resourceContentId]/+page.svelte

This endpoint is one that should adhere to the new status workflow of 'company' review, not 'manager'.

Update manager api endpoint to company

---

src/lib/components/editor/ContentEditorSwapButton.svelte
src/lib/components/editor/ScrollSyncLockToggle.svelte
src/lib/components/editor/TiptapDiffRenderer.svelte
src/lib/components/editor/TiptapRenderer.svelte
src/lib/stores/scrollSync.svelte.ts
src/lib/stores/scrollSync.ts
src/routes/resources/[resourceContentId]/+page.svelte
tsconfig.json

This conversion includes a completly encapsulated state tracking using runes that prevents the application from erroring out when the component that uses the scrollSync is not in Runes mode itself

Convert scrollSync to svelte5

---

src/lib/components/comments/CommentButton.svelte
src/lib/components/comments/CommentTextArea.svelte
src/lib/components/comments/CommentThread.svelte
src/lib/components/comments/CommentsSidebar.svelte
src/lib/components/comments/InlineComment.svelte
src/lib/components/comments/SidebarComment.svelte

comments upgrade
Test:
- Everything around comments

comments upgrade

---

src/lib/components/editor/LinkResourceReferenceButton.svelte
src/lib/components/editorMarkPopouts/ResourcePopout.svelte
src/lib/components/users/NewUserModal.svelte
src/lib/stores/parent-resources.ts
src/routes/+layout.svelte
src/routes/users/+page.svelte

svelte5 Upgrade to Users and layout.ts
convert $parentResources store to context
Test:
- Users dashboard with user actions
- side menu functionality with all roles
- InlineResourceReferenceLinks
- Linking one resource to another

Update users svelte5

---

src/lib/components/projects/ProjectTable.svelte
src/routes/(dashboard)/PublisherDashboard.svelte

... also for 'My Projects' Tab in Publishers dashboard

add text-error to class if the days is < 0 for ProjectTable components

---

src/routes/(dashboard)/EditorDashboard.svelte

Prevents users from sending to company review if the status is already in company review.

Fixing Bulk Send To Company Review Bug

---

src/routes/(dashboard)/PublisherDashboard.svelte

Create New Resource Frontend

---

src/lib/components/Modal.svelte
src/lib/components/audioPlayer/AudioPlayerModal.svelte

Update Modal to close when Escape is pressed
Apply closeWhenClickOutside for AudioPlayer

Update Modal to have optional closeWhenClickOutside

---

src/routes/projects/new/+page.svelte
src/routes/projects/new/ProjectContentSelector.svelte
src/routes/resources/[resourceContentId]/sidebar-content-store.ts

Depends on https://github.com/BiblioNexusStudio/aquifer-server/pull/652.

Allow translated items to be selected for new projects.

---

src/lib/utils/date-time.ts
src/routes/(dashboard)/notifications-helpers.ts

Fix Deals With Errors Thrown By Date Time TS And Also Filters Notifications Down To Comments

---

package.json
src/lib/components/Modal.svelte
src/lib/components/Tooltip.svelte
src/lib/components/editor/LinkBibleReferenceButton.svelte
src/lib/components/resources/ContentArea.svelte
src/routes/resources/[resourceContentId]/+page.svelte
yarn.lock

- Shortcuts were added using the following library: [Keystrokes JS](https://github.com/RobertWHurst/Keystrokes).
- Shortcuts handling sensitive logic were wrapped in the same logic as the visible buttons. 
- Shortcuts are unbound when the resource/content page is destroyed. This should help avoid errors generated by mistaken inputs or execution of untended business logic.

BIB-856 - Keyboard Short Cuts

---

src/lib/components/Table.svelte
src/routes/(dashboard)/EditorDashboard.svelte
src/routes/(dashboard)/ManagerDashboard.svelte

This allows the exit button in the resource page to bring the user back to the page they were on before navigating away.

Added Search Param PageNumber To Paginated Table

---

src/routes/projects/new/ProjectContentSelector.svelte
src/routes/projects/new/ProjectContentSelectorTable.svelte

Add Selected item and word count to project create

---

.gitignore
src/lib/components/references/bibleTextReferenceFetcher.ts
src/lib/utils/bible-book-fetcher.ts
src/lib/utils/reference.ts

`resources/381634` on dev/qa has some examples of verses from Nemiah. The backend is already deployed.

Bib 853 versification UI updates

---

src/lib/components/references/bibleTextReferenceFetcher.ts
src/lib/utils/bible-passage-fetcher.ts
src/lib/utils/bible-passage-utils.ts
src/lib/utils/bible-versification-fetcher.ts

There was an issue where the content of passages that contained multiple verses were not displaying the passage content correctly.

Refactor versification UI to handle verse content correctly

---

src/lib/components/references/bibleTextReferenceFetcher.ts

Fixes "1-1" verse reference display (e.g. https://qa.admin.aquifer.bible/resources/201388)

Fix references to verse 1.

---

src/lib/components/references/bibleTextReferenceFetcher.ts
src/lib/utils/bible-versification-fetcher.ts

See https://github.com/BiblioNexusStudio/aquifer-server/pull/733 for details.

Handle full mappings from server and fix verse 0 problem.

---

src/lib/components/DatePicker.svelte
src/lib/stores/reporting.ts
src/lib/utils/sveltekit-search-params.ts
src/routes/reporting/[slug]/+page.svelte

Also, the refresh button is now hidden until param updates are made.

Reporting Page Now Indicates When Loading

---

src/lib/components/editor/EditorToolbar.svelte
src/lib/components/editor/LinkBibleReferenceButton.svelte

Now Calling Api On All Languages

BIB-905 - Allow Bible Reference Association Update for All Languages - Bugs

---

src/lib/components/mentions/mentions.svelte.ts

The user list for mentions still shows when there are no matches to the user's input. This commit changes it so that the user list will not display when there are not matches.
Also, this includes refinements to managing spaces surrounding a mention.

Bugfix hide empty user list

---

src/routes/+layout.svelte

Revert recent logging changes in attempt to bring back missing custom dimensions on some errors.

revert error logging changes

---

src/lib/components/references/bibleTextReferenceFetcher.ts
src/lib/logger.ts

There wasn't any trace level logging supported so I added it.

Introduce trace level logging and downgrade versification error to trace.
