BiblioNexusStudio/content-manager-web

src/app.html
src/routes/+layout.svelte

Rather than showing any sort of loading indicator, we were previously just showing a blank white screen and on longer loads it seemed like the page was broken. This way the user knows something is happening.

add initial loading spinner instead of plain white screen

---

src/routes/resources/[resourceContentId]/+page.svelte

Aimed to condense the space as much as possible without refactoring the license button. With [713](https://linear.app/biblionexus/issue/BIB-713/add-option-for-editor-scrolling-to-stay-synced) on the horizon, I'm disinclined to change the license button.

Update spacing around word count and license info

---

.github/actions/build-and-deploy-to-env/action.yml
.github/workflows/post-merge.yml
.github/workflows/pre-merge.yml

To make builds/deployments fully reproducible and avoid untimely failures this pins all GitHub Action versions.

pin GitHub Action versions

---

src/routes/resources/[resourceContentId]/+page.svelte

After an Editor clicked 'Send to Review', the
scroll position of the editor divs was not being reset properly
during resource page transition into the next task.

Fix issue where scroll position was not resetting

---

src/lib/components/resources/menus/CurrentTranslations.svelte
src/lib/components/resources/menus/Related.svelte

The `Translations` and `Related Content` buttons did not work in Safari.
The fix was to add `tabindex` and `role` to the related elements.
An alternate fix is to use the `<details><summary>` [version of the dropdown](https://daisyui.com/components/dropdown/).

Daisyui focus button on resource page not working in Safari

---

src/lib/components/MachineTranslationRating.svelte
src/lib/components/editor/AiTranslateToolbarButton.svelte
src/lib/types/resources.ts
src/routes/resources/[resourceContentId]/+page.svelte

When there are translated Fia steps that haven't been rated yet, the user will be prompted in the assign modal to rate it. All unrated translations will be rated at once.

add support for handling missing translation ratings when assigning Fia content to new user

---

src/lib/stores/auth.ts
src/lib/types/base.ts
src/routes/resources/[resourceContentId]/+page.svelte
src/routes/resources/[resourceContentId]/TranslationSelector.svelte

I modified `src/routes/resources/[resourceContentId]/TranslationSelector.svelte` to handle the value of the `languageid` as a number to take advantage of Svelte's type inference and help us avoid calling `toString()` and `parseInt()` when interacting with language Ids. This made sense as a language id is only ever a string when used in the value of the `option` html element and is never a string on the server.

Bib 710 modify view edit page for community reviewer users

---

src/lib/components/resources/Content.svelte
src/lib/components/resources/content-components/Text.svelte
src/routes/resources/[resourceContentId]/+page.svelte

To align the Fia step controls, I had to move the display of the book and differences checkbox to the `Text` component. This helped clean up a small amount of logic that was unnecessary in the `+page.svelte` as well.

Fix Fia step navigation alignment

---

src/routes/resources/[resourceContentId]/+page.svelte

When community users try to translate an item and already have one assigned, they need some feedback.
I implemented a simple message utilizing the error modal that was already in place and update their `canCommunityTranslate` permission check to `false`

Add modal error message for community multitranslate

---

src/app.html

The tap preload didn't differentiate between a regular click and a middle-click / ctrl+click (i.e. a click to open a new tab). So any time someone would do that, it would hit the API twice. This surely contributes to the performance issues with the database when someone quickly opens several items at once as new tabs.

Remove tap preload

---

src/lib/components/MachineTranslationRating.svelte
src/lib/components/StarRating.svelte
src/routes/resources/[resourceContentId]/+page.svelte

Instead of using Svelte reactivity to detect changes in the machine translation rating and PATCH it, directly PATCH based off of the input fields changing. Also adds a check to make sure the current user is assigned the content to rate since that came up in my testing.

fix some edge cases with machine translation ratings

---

src/lib/components/editorMarkPopouts/MarkPopout.svelte

fix tiptap popouts so they appear right next to content

---

package.json
vite.config.ts

This gets used by the `aquifer-utilities` `get-app-insights-js-error-context.js` script to show errors that tie to the source map.

add build-with-source-maps script

---

tsconfig.json

Resolv the TS error: `An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.ts(5097)` when using the new `*.svelte.ts` extension in an import

Update tsconfig.json to fix import error for new `*.svelte.ts` files

---

src/routes/resources/[resourceContentId]/BibleReferencesSidebar.svelte

This bug was found while testing BIB-811 in QA. The following [resource](https://qa.admin.aquifer.bible/resources/49976) in Portuguese does not have a default bible for its language. It is supposed to fallback to BSB and does, but the new dropdown does not display BSB. 
This PR fixes that issue.

BIB-811 - Resolving Missing Bible For Language Bug

---

src/lib/components/editor/EditorToolbar.svelte

This bug is the result of wanting the editor controls to be rendered in a dropdown when the editor becomes too narrow to display all of the icons.
VS
The `ResizeObserver` is used to observe elements on the page rather than the entire document. Exactly what we want.
However, this is incredibly hard to reproduce. I was not able to reproduce it using multiple browsers and throttling on both the network and the CPU. Insight logs show this error affecting Chrome and Edge with resources of varying lengths.
According to posts on Stackoverflow and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#observation_errors), the solution is to add a `debounce` or `requestAnimationFrame` to your `ResizeObserver`.
So, I added the `requestAnimationFrame` to the ResizeObserver.

Update ResizeObserver to use requestAnimationFrame

---

src/lib/components/help/Document.svelte
src/routes/(dashboard)/+page.ts
src/routes/(dashboard)/CommunityReviewerDashboard.svelte
src/routes/+layout.svelte

Most of the Help content does not apply to Community Users. So, this ticket has us implementing a `Help` tab on their Dashboard. 
I used a `localstorage` flag to simulate a 'first login' check. If they clear the storage in their browser, the disruption is minimal and this prevents us from having to build out a backend solution for login tracking.

Bib 844 for community reviewers only show helpful how to documents

---

src/lib/components/editor/TiptapRenderer.svelte
src/lib/components/editor/createEditor.ts
src/routes/+layout.svelte
src/routes/resources/[resourceContentId]/+page.svelte

The unsafe mutation was caused by a race condition where the editor had pending transaction events when the next animation frame was called. This resulted in the ownership of `editor` being different from the one that the transaction was called from when the value was `set`.

Bugfix Unsafe mutation

---

src/lib/components/comments/CommentThread.svelte
src/lib/components/comments/SidebarComment.svelte
src/routes/(dashboard)/+page.ts
src/routes/(dashboard)/CommunityReviewerDashboard.svelte
src/routes/(dashboard)/EditorDashboard.svelte
src/routes/(dashboard)/ManagerDashboard.svelte
src/routes/(dashboard)/PublisherDashboard.svelte
src/routes/(dashboard)/notifications-helpers.ts
src/routes/resources/[resourceContentId]/+page.svelte

- The page no longer refreshes when the "mark all as read" function is triggered. Instead, the changed comments are marked as read.
- When the user clicks on one of the notifications, the user goes to the resource page, the comment bar opens, and the comment is highlighted.

BIB-857 - AC Misses

---

src/lib/utils/reference.ts

Svelte5 doesn't consistently work when comparing enums:
https://github.com/sveltejs/svelte/issues/11502
Solution" Convert them explicitly to upper-case strings first, then compare
Also looked into doing preprocess with vite for typescript, but it's already set to `script`, and it doesn't work doing both. Also, syntax breaks to preprocess with only `typescript` and not `script`. I also don't think it's worth doing something that affects server-level when the solution above fixes it.

Fix rtl verses to display correctly in popup and sidebar

---

src/lib/components/Table.svelte

Since more tables are being paginated and pages with as many as 1000 items are available, this patch kicks the user back to page one if the user's current page is more significant than the available pages. This happens if a user has a table with 600 items and 100 items per page. If the user navigates to page 3 and then switches the total number of items to 1000, the user sees no items, and the pages are wrong. 
Image of bug:

Fixing Page Miss Match Bug

---

src/lib/components/Table.svelte

Users were not getting kicked back to page one if they selected "all" in the dropdown of paginated tables. Also added "pre" to the effect to avoid jumpy UI.

Fixing All Items Selected In Drop Down Bug

---

src/lib/components/references/bibleTextReferenceFetcher.ts

There was an issue where if a passage had a verse mapping and it had bookTexts data, the wrong verse number would be shown in the passage display name and the sidebar body text.
I also took some time to reduce the noise in the file and extract some reused logic for clarity.

Bib 853 versification UI updates

---

src/lib/components/references/BibleTextReference.svelte
src/lib/components/references/bibleTextReferenceFetcher.ts
src/lib/utils/bible-versification-fetcher.ts
src/lib/utils/reference.ts

Handles the breaking change in [aquifer-server](https://github.com/BiblioNexusStudio/aquifer-server/pull/722) which returns versification mappings with multiple target verses for a single source verse.
Resources for testing:
* Psalm 3: https://qa.admin.aquifer.bible/resources/41072 (English with verse 0 data)
* Psalm 3: https://qa.admin.aquifer.bible/resources/385014 (Russian mapping with a verse 1 superscript shift and thus a higher max verse number than English)
* Psalm 11: https://qa.admin.aquifer.bible/resources/40541 (English with verse 0 data)
* Psalm 11: https://qa.admin.aquifer.bible/resources/385015 (Russian mapping to a different chapter as well as a combined verse 1 superscript and text and thus the same max verse number as English)
Working verse 0 display as superscript: …

Handle multiple target verse mappings and correctly display verse 0.

---

.gitignore
src/lib/components/references/bibleTextReferenceFetcher.ts

Fixes verse reference display for the following scenarios:
* Single source verse with multiple target verses (fixes missing verse 68 in "Неемии 7:67*" reference in https://qa.admin.aquifer.bible/resources/385016)
* Multiple source verses that all map to one target verse (fixes "Псалтирь 10:1-1*" reference in https://qa.admin.aquifer.bible/resources/385017).
* Fetching verse 0 in addition to only verse 1 but verse 0 doesn't exist (fixes "Rev. 9:1-1" reference in https://qa.admin.aquifer.bible/resources/1434).

Fix verse reference display.

---

src/routes/resources/+page.svelte

Note: This doesn't prevent users from manually updating the URL (e.g. `/resources?isNotApplicable=true`) because the back-end doesn't prevent this search for non-publishers.

Only show N/A filter checkbox to Publishers.

---

src/lib/components/references/bibleTextReferenceFetcher.ts
src/lib/utils/bible-passage-fetcher.ts
src/lib/utils/bible-versification-fetcher.ts

This fixes a 400 when fetching versifications with Bible ID 0 by ensuring consistent Bible selection logic for both fetching Bible passage text and Bible versifications.
See also https://biblionexusworkspace.slack.com/archives/C0662HZ7RKM/p1742600035089939.

Set fallback Bible to 1 for fetching versification mappings.

---

src/routes/resources/+page.svelte

Puts back classes removed [here](https://github.com/BiblioNexusStudio/content-manager-web/pull/613/files#diff-903a8cfd9beda8c2f18acd1573fa6a7ed2d31b41af980671e906f03bc68d23c8L156-L157) which results in left justification of checkbox labels and right justification of checkboxes.

Fix alignment of filter checkboxes.

---

src/lib/components/references/BibleTextReference.svelte
src/lib/components/references/bibleTextReferenceFetcher.ts

Fixes https://qa.admin.aquifer.bible/resources/385020 where `Psalms 11:1-7` in the ENG is mapping to `Psalms 11:1-7*` in the LS1910 due to ENG having verse 0 but LS1910 not having verse 0.
Before:
After:
While I was in there I also improved the spacing when reading multiple chapters at once by adding padding over the "Chapter N" text (it was previously very difficult to quickly find the correct chapter in large blocks of text):

Fix asterisk display.

---

src/lib/components/references/bibleTextReferenceFetcher.ts

Fixes:
* Fix passage filtering when spanning multiple books of Bible text.  I don't know if we ever show references across multiple books in practice, though.
* Filter out chapters/verses where there is no content to avoid errors.  This should only happen due to unexpected data.

Fix multi-book filtering and handle weird data cases.

---

src/routes/+layout.svelte

When catching an unhandled error, we are only logging the error which can be cryptic at times. In an attempt to gain more insight into these errors, I've expanded the `onError` fn in the `+layout.svelte` file to log all parameters available from the error event.

expand layout onError to log all available error info

---

src/lib/components/mentions/mentions.svelte.ts

Bugfix: when the user began a mention and then decided to cancel the comment, the state of the user list for mentions was not being reset.

Reset mention state when destroy method is called
